Loja/config/routes.rb
Rails.application.routes.draw do
	
  resources :line_items
  resources :carts
  resources :produtos


  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  
  root 'produtos#index'
  get 'line_items', to: 'line_items#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Loja/app/models/produto.rb
class Produto < ApplicationRecord
  before_destroy :not_refereced_by_any_line_item
  belongs_to :user, optional: true
  
  has_many :line_items

  mount_uploader :image, ImageUploader
  serialize :image, JSON 
  

  validates :Nome, :Descrição, :Preço, :Peso, :Quantidade, presence: true
  validates :Descrição, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :Nome, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
  validates :Preço, length: { maximum: 7 }, numericality: {greater_than: 0, message: "O preço tem que ser maior que 0."}
  validates :Peso, length: { maximum: 7 }, numericality: {greater_than: 0, message: "O peso tem que ser maior que 0."}
  validates :Quantidade, length: { maximum: 7 }, numericality: {greater_than_or_equal_to: 1, message: "A quantidade tem que ser maior que ou igual a 1."}
  validates :image, presence: true
  
  
  private
  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Item presente")
      throw :abort
    end
  end

end

Loja/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.order("created_at desc")
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = current_user.produtos.build
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = current_user.produtos.build(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto foi destruido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:Nome, :Descrição, :Preço, :Quantidade, :Peso, :image)
    end
end

Loja/app/helpers/produtos_helper.rb
module ProdutosHelper
end

Loja/app/views/produtos/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @produto, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :Nome , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
            <div class="field">
            <div class="control">
              <%= f.input :Preço, required: true, input_html: {class: "input" , step: 0.1, min: 0, maxlength: 7}, wrapper: false, label_html: { class:"label" },decimal: true, step: 0.1 %>
            </div>
          </div>
          </div>

          

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :Descrição, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
            <div class="control">
              <%= f.input :Quantidade, required: true, input_html: { class: "input" , step: 0.1, min: 0, maxlength: 7}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.input :Peso, required: true, input_html: { class: "input" , step: 0.1, min: 0, maxlength: 7}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        

        
        <div class="field">
          <div class="control">
            <label class="label">Adicionar imagens</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, required: true, as: :file, input_html: { class:"file-input produto-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Escolha um arquivo…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-light' %>
            <%= link_to 'Cancel', produtos_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

Loja/app/views/produtos/edit.html.erb
<% content_for :header do %>
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editando o produto
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', produto: @produto %>
</div>

Loja/app/views/produtos/index.html.erb
<% content_for :header do %>
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Produtos da Docarela
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="produto-index-grid pt4">
  <% @produtos.each do |produto| %>

    <div class="produto border-light">
      <div class="produto-thumb">


         <%= link_to image_tag(produto.image_url(:thumb)), produto %>
   



      <% if produto.Quantidade? %>
        <div class="Quantidade">
          <span class="tag is-dark">Quantidade: <%=produto.Quantidade %></span>
        </div>
      <% end %>


      </div>


    <div class="pa3">

      <h3 class="fw7 f4 Nome"><%= link_to produto.Nome, produto %></h3>
      <p class="has-text-gray fg pt1">Vendido por <%= produto.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 Preço"><%= number_to_currency(produto.Preço) %></p>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
           <%= link_to 'Editar', edit_produto_path(produto), class: "button is-small" %>
           <%= link_to 'Deletar', produto, method: :delete, data: { confirm: "Você tem certeza ?" }, class: "button is-small" %>
        <% end %>
       <% end %>

    </div>
  </div>
  <% end %>
</div>

Loja/app/views/produtos/new.html.erb
<h1 class="title is-2">Novo Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

Loja/app/views/produtos/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section produto-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @produto.Nome %></h1>

      <ul class="pv1">
        
      <div class="feature-image">
        <%= image_tag(@produto.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Descrição</h3>
      <%= @produto.Descrição %>


      <h3 class="subtitle is-4 pt5">Dados</h3>

      <table class="table is-narrow">
        <% if @produto.Preço %>
        <tr>
          <td class="has-text-weight-bold">Preço:</td>
          <td><%= @produto.Preço %> R$</td>
        </tr>
        <% end %>

        <% if @produto.Peso %>
          <tr>
            <td class="has-text-weight-bold">Peso:</td>
            <td><%= @produto.Peso %> Kg</td>
          </tr>
        <% end %>

        <% if @produto.Quantidade %>
          <tr>
            <td class="has-text-weight-bold">Quantidade:</td>
            <td><%= @produto.Quantidade %>x</td>
          </tr>
        <% end %>
      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@produto.Preço) %></h4>
        <p class="has-text-centered mb4">Vendido por <%= @produto.user.name %></p>
        <%= button_to 'Adicionar ao carrinho', line_items_path(produto_id: @produto), class: 'button is-light add-to-cart' %>
        <div class="bg-white pa2 pl4 align-items-center">
          <%= link_to 'Voltar', produtos_path, class: 'button is-light voltar' %> 
          <%= link_to 'Home', root_path, class: 'button is-light home' %>
        </div>
      </div>
    </div>
  </div>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_produto_path(@produto), class: 'button' %>
    <%= link_to 'Deletar', produto_path(@produto), method: :delete, data: { confirm: "Você tem certeza ?" }, class: "button is-danger" %>
  <% end %>
   <% end %>
</section>