Loja/config/routes.rb
Rails.application.routes.draw do
	
  resources :line_items
  resources :carts
  resources :produtos


  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  
  root 'produtos#index'
  get 'line_items', to: 'line_items#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Loja/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docarela</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-pink" role="navigation" aria-label="main navigation">
      
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Docarela</h1>

        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
            
            <% if user_signed_in? %>

             <% if total_cart_items %>
              <%= link_to cart_path(@cart), class:"navbar-item button mr1 is-white" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
               
                </span>
              <% end %>
            <% end %>

            
            
            <% if current_user.admin? %>
              <%= link_to 'Vender', new_produto_path, class: "navbar-item button is-white" %>
              <% else %>
               <%= link_to 'Comprar', produtos_path, class: "navbar-item button is-white" %>
            <% end %>
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Conta', edit_user_registration_path, class: "navbar-link is-white" %>
                <div class="navbar-dropdown is-right ">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-white mr1" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-white"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>